version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync build/ s3://slp1.project-andy.com --delete

artifacts:
  files:
    - '**/*'
  base-directory: build

